import json

with open('web/app/web/page.tsx', 'r', encoding='utf-8') as f:
    lines = f.readlines()

new_lines = lines[:1225] + [
    '            }}>\n',
    '              <div>\n',
    '                <div style={{ fontSize: \'22px\', fontWeight: 900, fontFamily: \'monospace\', color: \'#D4AF37\' }}>\n',
    '                  ${parseFloat(room.rp || 0).toLocaleString()}\n',
    '                </div>\n',
    '                <div style={{ fontSize: \'9px\', color: \'rgba(255,255,255,0.3)\', letterSpacing: \'1px\' }}>PER NIGHT</div>\n',
    '              </div>\n',
    '              <button \n',
    '                onClick={() => onBook(room.dept?.replace(\'Z-19-\', \'\') || \'STANDARD\')}\n',
    '                className="book-btn"\n',
    '                style={{\n',
    '                  padding: "10px 20px", background: "rgba(0,242,255,0.12)", border: "1px solid rgba(0,242,255,0.4)",\n',
    '                  borderRadius: "10px", color: "#00F2FF", fontSize: "11px", fontWeight: 900,\n',
    '                  letterSpacing: "1px", cursor: "pointer"\n',
    '                }}\n',
    '              >\n',
    '                RESERVE NOW\n',
    '              </button>\n',
    '            </div>\n',
    '\n',
    '          </div>\n',
    '        </div>\n',
    '\n',
    '      </div>\n',
    '    </div>\n',
    '\n',
    '    {/* ============================================\n',
    '        CAREERS TEASER — We\'re Hiring\n',
    '        Links to /web/careers (Sovereign Talent Engine)\n',
    '    ============================================ */}\n',
    '    <CareersTeaser />\n',
    '\n',
    '  );\n',
    '}\n',
    '\n',
    '// ============================================\n',
    '// CAREERS TEASER — "We\'re Hiring" Section\n',
    '// Reads live open positions from Sovereign Talent Engine\n',
    '// ============================================\n',
    'function CareersTeaser() {\n',
    '  const [count, setCount] = useState(0);\n',
    '  const [depts, setDepts] = useState<string[]>([]);\n',
    '\n',
    '  useEffect(() => {\n',
    '    fetch(`${API}/hr/talent/vacancies?status=PUBLISHED`)\n',
    '      .then(r => r.json())\n',
    '      .then(d => {\n',
    '        const vacs = d.vacancies || [];\n',
    '        setCount(vacs.length);\n',
    '        const uniqueDepts = Array.from(new Set(vacs.map((v: any) => v.department))).slice(0, 6) as string[];\n',
    '        setDepts(uniqueDepts);\n',
    '      })\n',
    '      .catch(() => {});\n',
    '  }, []);\n',
    '\n',
    '  if (count === 0) return null;\n',
    '\n',
    '  return (\n',
    '    <section style={{ background: "linear-gradient(135deg, rgba(0,242,255,0.03) 0%, rgba(212,175,55,0.04) 100%)", borderTop: "1px solid rgba(255,255,255,0.05)", padding: "80px 40px", textAlign: "center" }}>\n',
    '      <div style={{ maxWidth: "900px", margin: "0 auto" }}>\n',
    '        <div style={{ display: "inline-flex", alignItems: "center", gap: "10px", background: "rgba(57,255,20,0.08)", border: "1px solid rgba(57,255,20,0.25)", borderRadius: "50px", padding: "8px 20px", fontSize: "12px", color: "#39FF14", fontWeight: 800, letterSpacing: "2px", marginBottom: "25px" }}>\n',
    '          <span style={{ width: "8px", height: "8px", borderRadius: "50%", background: "#39FF14", display: "inline-block", boxShadow: "0 0 8px #39FF14", animation: "pulse 2s infinite" }} />\n',
    '          {count} POSITION{count !== 1 ? "S" : ""} OPEN NOW\n',
    '        </div>\n',
    '        <h2 style={{ fontFamily: "\\"Cinzel\\", serif", fontSize: "38px", color: "#FFF", margin: "0 0 12px 0", letterSpacing: "2px" }}>\n',
    '          We\'re <span style={{ color: "#D4AF37" }}>Hiring</span>\n',
    '        </h2>\n',
    '        <p style={{ color: "#777", fontSize: "15px", lineHeight: "1.7", marginBottom: "25px" }}>\n',
    '          Join the Miracle team and be part of a world-class luxury hospitality experience.<br />UAE Visa · Accommodation · Medical Insurance · Annual Flight · 30 Days Leave.\n',
    '        </p>\n',
    '        {depts.length > 0 && (\n',
    '          <div style={{ display: "flex", gap: "10px", justifyContent: "center", flexWrap: "wrap", marginBottom: "30px" }}>\n',
    '            {depts.map(d => (\n',
    '              <span key={d} style={{ background: "rgba(212,175,55,0.08)", border: "1px solid rgba(212,175,55,0.2)", color: "#D4AF37", fontSize: "11px", padding: "6px 16px", borderRadius: "50px", fontWeight: 600 }}>{d}</span>\n',
    '            ))}\n',
    '          </div>\n',
    '        )}\n',
    '        <a href="/web/careers" style={{ display: "inline-block", background: "linear-gradient(135deg, #D4AF37 0%, #B8960C 100%)", color: "#000", padding: "18px 50px", borderRadius: "14px", fontWeight: 900, fontSize: "15px", textDecoration: "none", letterSpacing: "1px", boxShadow: "0 10px 30px rgba(212,175,55,0.3)", transition: "0.3s" }}>\n',
    '          VIEW ALL CAREERS →\n',
    '        </a>\n',
    '      </div>\n',
    '    </section>\n',
    '  );\n',
    '}\n'
]
with open('web/app/web/page.tsx', 'w', encoding='utf-8') as f:
    f.writelines(new_lines)
