// 🤖 AUTO-GENERATED BY KERNEL BRAIN. DO NOT EDIT MANUALLY.
export const KERNEL_VERSION = 'V66.0-SOVEREIGN-SRE';

export const ZONE_PERMISSIONS: Record<string, string[]> = {
  // ── CORE OPERATIONS ──────────────────────────────────────────
  'Z-07': ["CDO", "GM", "ADMIN", "STAFF", "VISITOR"],
  'Z-05': ["CDO", "GM", "ADMIN", "FD", "STAFF", "VISITOR"],
  'Z-06': ["CDO", "GM", "ADMIN", "POS", "SPA", "STAFF", "VISITOR"],
  'Z-08': ["CDO", "GM", "ADMIN", "FD", "POS", "SPA", "ACC", "STAFF", "VISITOR"],
  'Z-16': ["ANY"],
  'Z-17': ["ANY"],
  // ── GUEST & MARKETING ────────────────────────────────────────
  'Z-10': ["CDO", "GM", "ADMIN", "FD", "STAFF", "VISITOR"],
  'Z-GUEST': ["CDO", "GM", "ADMIN", "STAFF", "GUEST", "VISITOR"],
  // ── PROPERTY & ASSET ─────────────────────────────────────────
  'Z-30': ["CDO", "GM", "ADMIN", "ACC", "STAFF", "VISITOR"],
  'Z-31': ["CDO", "GM", "ADMIN", "ACC", "STAFF", "VISITOR"],
  // ── HR & PEOPLE ──────────────────────────────────────────────
  'Z-09': ["CDO", "GM", "ADMIN", "HR", "DOCTOR", "STAFF", "VISITOR"],
  'Z-DOCTOR': ["CDO", "GM", "ADMIN", "DOCTOR"],
  'Z-2B': ["CDO", "GM", "ADMIN", "HR", "STAFF"],
  'Z-18': ["CDO", "GM", "ADMIN", "HR", "STAFF", "VISITOR"],
  // ── FINANCE & ACCOUNTS ────────────────────────────────────────
  'Z-11':      ["CDO", "GM", "ADMIN", "ACC", "DEPT_HEAD", "VISITOR"],
  'Z-11B':     ["CDO", "GM", "ADMIN", "ACC"],
  'Z-11C':     ["CDO", "GM", "ADMIN", "ACC"],
  'Z-1B':      ["CDO", "GM", "ADMIN", "ACC"],
  'Z-VAULT':   ["CDO", "GM", "ADMIN", "ACC", "DEPT_HEAD", "WELLNESS_MANAGER", "DEPT_MANAGER"],
  'Z-DEPT-GW': ["CDO", "GM", "ADMIN", "ACC"],
  'Z-MASTER':  ["CDO", "GM", "ADMIN", "ACC"],
  'Z-INTEL':   ["CDO", "GM", "ADMIN", "ACC"],
  // ── INVENTORY & OPERATIONS ───────────────────────────────────
  'Z-12': ["CDO", "GM", "ADMIN", "POS", "HK", "MN", "STAFF", "VISITOR"],
  // ── SERVICE EMPIRE ────────────────────────────────────────────
  'Z-26': ["CDO", "GM", "ADMIN", "STAFF", "VISITOR"],
  'Z-27': ["CDO", "GM", "ADMIN", "SPA", "STAFF", "VISITOR"],
  'Z-29': ["CDO", "GM", "ADMIN", "FB", "STAFF", "VISITOR"],
  // ── INTELLIGENCE & MEDIA ─────────────────────────────────────
  'Z-14': ["CDO", "GM", "ADMIN", "STAFF", "VISITOR"],
  'Z-CC': ["CDO", "GM", "ADMIN"],
  'Z-19': ["CDO", "GM", "ADMIN", "VISITOR"],
  'Z-20': ["CDO", "GM", "ADMIN", "SYNAPSE", "VISITOR"],
  // ── PORTALS ──────────────────────────────────────────────────
  'Z-WEB': ["CDO", "GM", "ADMIN", "STAFF", "VISITOR"],
  'Z-OWNER': ["CDO", "GM", "ADMIN", "STAFF", "VISITOR"],
  // ── SYSTEM & INFRA ────────────────────────────────────────────
  'Z-21': ["CDO", "GM", "ADMIN"],
  'Z-23': ["CDO", "GM", "ADMIN"],
  'Z-CTRL': ["CDO", "SUPER_ADMIN"],
  // ── RESERVED ─────────────────────────────────────────────────
  'Z-LOGIN': ["PUBLIC"],
  'DEFAULT': ["INTERNAL_AI_ONLY"],
};

export const MASTER_ZONES = [
  { id: 'Z-07', name: 'Clinical Command', path: '/dashboard', icon: '🖥️' },
  { id: 'Z-30', name: 'Ward ADT PMS', path: '/dashboard/pms', icon: '🏥' },
  { id: 'Z-05', name: 'OPD Scheduling', path: '/dashboard/reservations', icon: '🩺' },
  { id: 'Z-06', name: 'Pharmacy Revenue', path: '/dashboard/pos', icon: '💊' },
  { id: 'Z-26', name: 'Ambulance & Emergency', path: '/emergency', icon: '🚑' },
  { id: 'Z-RERS', name: '🚨 Emergency Grid', path: '/emergency', icon: '🚨' },
  { id: 'Z-27', name: 'LIS Diagnostic Labs', path: '/dashboard/wellness', icon: '🔬' },
  { id: 'Z-29', name: 'Patient Dietary & Meals', path: '/dashboard/z29-gastronomy', icon: '🍱' },
  { id: 'Z-08', name: 'Billing / Discharges', path: '/dashboard/checkout', icon: '💳' },
  { id: 'Z-16', name: 'Clinical Alarm Tickets', path: '/dashboard/issue-tickets', icon: '🚨' },
  { id: 'Z-17', name: 'Solve Alarm Tickets', path: '/dashboard/solve', icon: '🛠️' },
  { id: 'Z-14', name: 'Medical Education Lab', path: '/dashboard/media-lab', icon: '📚' },
  { id: 'Z-CC', name: 'Clinical Note Assistant', path: '/dashboard/content-creator', icon: '🤖' },
  { id: 'Z-18', name: 'Biometric Staff Portal', path: '/dashboard/portal', icon: '👁️' },
  { id: 'Z-12', name: 'Pharmacy Inventory Matrix', path: '/dashboard/inventory', icon: '💊' },
  { id: 'Z-DOCTOR', name: 'Physician Command Portal', path: '/dashboard/doctor', icon: '🩺' },
  { id: 'Z-09', name: 'Clinical Roster / Staff', path: '/dashboard/hr', icon: '👥' },
  { id: 'Z-2B', name: 'AGI Doctor Recruiting', path: '/dashboard/hr?tab=AGI_RECRUIT', icon: '🤖' },
  { id: 'Z-10', name: 'Patient CRM Records', path: '/dashboard/crm', icon: '🤝' },
  { id: 'Z-19', name: 'Medical Policies', path: '/dashboard/policy', icon: '⚙️' },
  { id: 'Z-20', name: 'Synapse Nexus', path: '/dashboard/synapse', icon: '⚡' },
  { id: 'Z-11',      name: 'Medical Billing & TPA',     path: '/dashboard/accounts',                   icon: '📊' },
  { id: 'Z-1B',      name: 'Ledger Auth Gateway',        path: '/dashboard/accounts?tab=25',            icon: '🔐' },
  { id: 'Z-11B',     name: 'Accounting AGI',             path: '/dashboard/agi-accounts',               icon: '🧠' },
  { id: 'Z-11C',     name: 'Sovereign Finance & Policy', path: '/dashboard/sovereign-finance',          icon: '🏛️' },
  { id: 'Z-VAULT',   name: 'Dept Vault',                 path: '/dashboard/accounts/vault',             icon: '🏦' },
  { id: 'Z-DEPT-GW', name: 'Batch Gateway',              path: '/dashboard/accounts/gateway',           icon: '🔏' },
  { id: 'Z-MASTER',  name: 'Master Ledger',              path: '/dashboard/accounts/master-ledger',     icon: '📒' },
  { id: 'Z-INTEL',   name: 'AGI Intelligence',           path: '/dashboard/accounts/intelligence',      icon: '🧠' },
  { id: 'Z-21', name: 'Hospital Settings', path: '/dashboard/settings', icon: '🔧' },
  { id: 'Z-23', name: 'Hospital Infrastructure', path: '/dashboard/infrastructure', icon: '☁️' },
  { id: 'Z-CTRL', name: 'Control Panel', path: '/dashboard/control-panel', icon: '🛡️' },
  { id: 'Z-GUEST', name: 'Patient Portal', path: '/dashboard/guest', icon: '🏥' },
  { id: 'Z-WEB',   name: 'Public Website', path: '/web', icon: '🌐' },
  { id: 'Z-OWNER', name: 'Director Portal', path: '/owner', icon: '🏆' },
  { id: 'Z-31',    name: 'Director Bridge', path: '/dashboard/pms?tab=requests', icon: '📬' },
  { id: 'DEFAULT', name: 'System Concierge', path: 'None', icon: '🌟' },
];

