// AUTO-GENERATED BY SOVEREIGN SURFACE INTELLIGENCE ENGINE v1.0
// Industry: cinema | Do not edit manually
// Generated: 2026-06-26 20:14 UTC

// Alias for cross-zone imports
export const SURFACE_CONFIG = {
  "industry": "cinema",
  "label": "Cinema & Entertainment System",
  "catalog_label": "Movies & Shows",
  "cart_label": "Booking Cart",
  "transaction_label": "Ticket",
  "categories": [
    {
      "id": "NOW",
      "name": "Now Showing",
      "icon": "🎬",
      "color": "#c026d3"
    },
    {
      "id": "COMING",
      "name": "Coming Soon",
      "icon": "🎞️",
      "color": "#9333ea"
    },
    {
      "id": "SNACKS",
      "name": "Snacks",
      "icon": "🍿",
      "color": "#f59e0b"
    },
    {
      "id": "DRINKS",
      "name": "Drinks",
      "icon": "🥤",
      "color": "#06b6d4"
    },
    {
      "id": "COMBOS",
      "name": "Combo Deals",
      "icon": "🎁",
      "color": "#16a34a"
    },
    {
      "id": "MERCH",
      "name": "Merchandise",
      "icon": "👕",
      "color": "#6366f1"
    }
  ],
  "quick_keys": [
    {
      "label": "Adult Ticket",
      "sku": "TKT-ADULT"
    },
    {
      "label": "Child Ticket",
      "sku": "TKT-CHILD"
    },
    {
      "label": "Senior Ticket",
      "sku": "TKT-SENIOR"
    },
    {
      "label": "Popcorn (Large)",
      "sku": "SNACK-POP-L"
    },
    {
      "label": "Combo 1",
      "sku": "COMBO-1"
    },
    {
      "label": "Combo 2",
      "sku": "COMBO-2"
    },
    {
      "label": "Gift Card",
      "sku": "GIFT"
    },
    {
      "label": "Refund Ticket",
      "sku": "REFUND"
    }
  ],
  "workflow": [
    {
      "step": 1,
      "id": "MOVIE",
      "label": "Select Movie",
      "icon": "🎬"
    },
    {
      "step": 2,
      "id": "SHOW",
      "label": "Select Showtime",
      "icon": "🕐"
    },
    {
      "step": 3,
      "id": "SEATS",
      "label": "Pick Seats",
      "icon": "💺"
    },
    {
      "step": 4,
      "id": "TYPE",
      "label": "Ticket Type",
      "icon": "🎫"
    },
    {
      "step": 5,
      "id": "ADDONS",
      "label": "Add Concessions",
      "icon": "🍿"
    },
    {
      "step": 6,
      "id": "PAYMENT",
      "label": "Payment & QR",
      "icon": "💳"
    }
  ],
  "fields": [
    {
      "name": "movie",
      "label": "Movie Title",
      "type": "text",
      "required": true
    },
    {
      "name": "showtime",
      "label": "Showtime",
      "type": "text",
      "required": true
    },
    {
      "name": "screen",
      "label": "Screen No.",
      "type": "text",
      "required": true
    },
    {
      "name": "seats",
      "label": "Seat Numbers",
      "type": "text",
      "required": true
    }
  ],
  "alerts": [
    {
      "id": "SOLD_OUT",
      "label": "Show Sold Out",
      "color": "#ef4444"
    },
    {
      "id": "FEW_SEATS",
      "label": "Only 5 Seats Left",
      "color": "#f59e0b"
    }
  ],
  "reports": [
    "Occupancy Rate",
    "Revenue per Screen",
    "Concession Sales",
    "Genre Performance",
    "Peak Day Analysis",
    "Member Bookings"
  ],
  "primary_color": "#c026d3",
  "accent_color": "#f5d0fe",
  "bg_gradient": "from-purple-950 to-fuchsia-900"
} as const;

export type SurfaceCategory = typeof SURFACE_CONFIG.categories[number];
export type SurfaceField = typeof SURFACE_CONFIG.fields[number];
export type SurfaceAlert = typeof SURFACE_CONFIG.alerts[number];
